[project]
name = "ai-web-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "jinja2>=3.1.6",
    "pydantic>=2.11.5",
    "python-dotenv>=1.1.0",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.34.3",
    "python-multipart>=0.0.9",
    "openai",
    "python-docx",
    "PyPDF2",
    "markdown",
    "pdfkit",
    "beautifulsoup4",  # Necesario para exportar a Word interpretando HTML
]
